name: onix_flutter_core_models
description: Onix Flutter core models
version: 0.0.3-beta.1
repository: https://github.com/OnixFlutterTeam/onix-flutter-core-models

environment:
  sdk: '>=3.0.0 <4.0.0'

